[patch] Added unlock all
IW4x/iw6x-client pull request #21
Opened 2020-09-19 21:02 UTC by FragsAreUs

2020-09-19 22:57 UTC, momo5502 requested changes

2020-09-19 22:57 UTC, momo5502 commented on src/client/module/patches.cpp
> +			//only Mp
If it is mp only, why did you enable the command for sp as well?
Please put it in patch_sp

2020-09-20 14:35 UTC, FragsAreUs commented on src/client/module/patches.cpp
> +			//only Mp
oof must have over locked

2020-09-20 14:41 UTC, FragsAreUs commented on src/client/module/patches.cpp
> +			//only Mp
should be fixed now

2020-09-20 15:18 UTC, momo5502 approved these changes

2020-09-20 15:18 UTC, merged