Add discord rpc, add speed to draw fps, add godmode
IW4x/iw6x-client pull request #44
Opened 2020-09-22 17:53 UTC by fedddddd

2020-09-22 17:56 UTC, RektInator commented
I don't think the source code of the discord rpc belongs in the client, you should use a submodule and create a script for premake.

2020-09-22 17:58 UTC, RektInator commented
The god command should just set the godmode flag on the entity, changing the max health is not godmode

2020-09-22 17:59 UTC, RektInator commented
I also think PRs should only have a single purpose, so 1 PR per bug fix / feature.

2020-09-22 18:01 UTC, fedddddd commented
Couldn't find the flag for godmode so i just did that but yea

2020-09-22 18:07 UTC, RektInator requested changes

2020-09-22 18:07 UTC, RektInator commented on src/client/module/discord_rpc.cpp
> +		int maxclients = game::native::Dvar_FindVar("sv_maxclients")->current.integer;
auto

2020-09-22 18:07 UTC, RektInator commented on src/client/module/discord_rpc.cpp
> +		int count = 0;
auto

2020-09-22 18:07 UTC, RektInator commented on src/client/module/discord_rpc.cpp
> +		for (int i = 0; i < maxclients; i++) {
auto, bracket on new line

2020-09-22 18:07 UTC, RektInator commented on src/client/module/discord_rpc.cpp
> +namespace
you could make this code part of the class defined below

2020-09-22 18:07 UTC, RektInator commented on src/client/module/command.cpp
> +        game::native::mp::g_entities[clientNum].maxHealth = game::native::mp::g_entities[clientNum].maxHealth == INT32_MAX ? 100 : INT32_MAX;
change the godmode flag instead

2020-09-22 18:07 UTC, RektInator commented on src/client/module/command.cpp
> +    command::add_sv("god", [&](int clientNum, command::params_sv&) {
bracket on next line

2020-09-22 18:50 UTC, momo5502 requested changes
use submodules

2020-09-22 18:50 UTC, momo5502 commented on src/client/module/fps.cpp
> +			if (game::native::mp::g_entities && game::native::Dvar_FindVar("cg_drawFPS")->current.integer > 2 && game::native::SV_Loaded()) {
empty line

2020-09-22 18:50 UTC, momo5502 commented on src/client/module/discord_rpc.cpp
> +		scheduler::loop(tick, scheduler::pipeline::renderer);
Renderer??? Really???

2020-09-22 18:50 UTC, momo5502 commented on src/client/module/discord_rpc.cpp
> +namespace
no, anonymous namespaces are better

2020-09-22 18:50 UTC, momo5502 commented on src/client/module/discord_rpc.cpp
> +	auto result = discord::Core::Create(757965986954477690, DiscordCreateFlags_Default, &core);
What's this id?

2020-09-22 18:50 UTC, momo5502 commented on src/client/module/discord_rpc.cpp
> +				activity.SetState(utils::string::va("Playing on %s", game::native::Dvar_FindVar("mapname")->current.string));
Might wanna localize that?

2020-09-22 18:50 UTC, momo5502 commented on src/client/module/discord_rpc.cpp
> +REGISTER_MODULE(discord_rpc);
Empty line?

2020-09-22 18:50 UTC, momo5502 commented on src/client/module/discord_rpc.cpp
> +	void tick() {
Bracket?

2020-09-22 18:50 UTC, momo5502 commented on src/client/module/discord_rpc.cpp
> +			{
That nesting level...

2020-09-22 18:51 UTC, momo5502 commented
Oh and the build pipeline? Might wanna create pull requests that actually build?

2020-09-22 19:08 UTC, RektInator commented on src/client/module/discord_rpc.cpp
> +namespace
alright, wasn't up-to-date on the new code guidelines for IW6x, my bad :P

2020-09-22 19:09 UTC, RektInator commented on src/client/module/discord_rpc.cpp
> +	auto result = discord::Core::Create(757965986954477690, DiscordCreateFlags_Default, &core);
He probably generated his own ID for the game on discord.com, I'd recommend generating one ourselves.

2020-09-22 19:09 UTC, fedddddd commented on src/client/module/discord_rpc.cpp
> +	auto result = discord::Core::Create(757965986954477690, DiscordCreateFlags_Default, &core);
Discord application clientid

2020-09-22 21:26 UTC, fedddddd commented
Yea if only discord game sdk was on github

2020-09-30 11:40 UTC, momo5502 requested changes
Please create a new pull request for the god mode. The discord integration will be done by the main developers

2020-09-30 11:40 UTC, momo5502 commented on deps/premake/discord-rpc.lua
> +			path.join(discordrpc.source, "src/serialization.h"),
You can use wildcards for that

2020-09-30 11:40 UTC, momo5502 commented on deps/premake/discord-rpc.lua
> +	rapidjson = path.join(dependencies.basePath, "rapidjson"),
That's not how our dependency management works

2020-09-30 11:40 UTC, momo5502 commented on src/client/module/command.cpp
> +        game::native::mp::g_entities[clientNum].flags ^= 1;
I want this command SP only

2020-09-30 11:40 UTC, closed without merging