added game console
IW4x/iw6x-client pull request #6
Opened 2020-09-16 09:35 UTC by obmiJ

2020-09-16 09:45 UTC, momo5502 commented
There are a few things that need to be changed, but still, it's apretty impressive commit.
I will finish the review once I have time. Meanwhile you can contact me on discord

2020-09-16 09:49 UTC, obmiJ commented
okay. i messaged you on discord.

2020-09-16 13:22 UTC, momo5502 requested changes

2020-09-16 13:22 UTC, momo5502 commented on src/client/module/game_console.cpp
> +GameConsole* game_console::con = new GameConsole;
You are leaking memory here. Is heap allocation really needed? If so, please use smart pointers

2020-09-16 13:22 UTC, momo5502 commented on src/client/module/game_console.cpp
> +void game_console::print(std::string& data)
const std::string&

2020-09-16 13:22 UTC, momo5502 commented on src/client/module/command.cpp
> +void command::execute(std::string input, bool sync)
const std::string&

2020-09-16 13:22 UTC, momo5502 commented on src/client/module/command.cpp
> +    std::string command = utils::string::to_lower(params[0]);
const auto command

2020-09-16 13:22 UTC, momo5502 commented on src/client/module/command.cpp
> +    std::string command = utils::string::to_lower(name);
const auto command

2020-09-16 13:22 UTC, momo5502 commented on src/client/module/game_console.cpp
> +	auto lines = utils::string::split(formatted, '\n');
const auto

2020-09-16 13:22 UTC, momo5502 commented on src/client/module/game_console.cpp
> +	std::string _input = utils::string::to_lower(input);
just reassign input, if you're not passing it as const reference, otherwise

2020-09-16 13:22 UTC, momo5502 commented on src/client/module/game_console.cpp
> +void game_console::find_matches(std::string input, std::vector<std::string>& suggestions, bool exact)
see comment below or const std::string& input

2020-09-16 13:22 UTC, momo5502 commented on src/client/module/game_console.cpp
> +bool game_console::match_compare(std::string& input, std::string& text, bool exact)
const std::string&

2020-09-16 13:22 UTC, momo5502 commented on src/client/module/game_console.cpp
> +	cl_char_event_hook.create(SELECT_VALUE(0x14023CE50, 0x1402C2AE0), cl_char_event_stub);
I guess it's fine as long as it works

2020-09-16 13:22 UTC, momo5502 commented on src/client/module/game_console.cpp
> +game_console::game_console()
Remove the constructor if it does nothing

2020-09-16 13:22 UTC, momo5502 commented on src/client/module/game_console.hpp
> +#define color_iw6 new float[4] { 0.0f, 0.7f, 1.0f, 1.0f }
...

2020-09-16 13:22 UTC, momo5502 commented on src/client/module/game_console.hpp
> +#define DARK_COLOR(color) new float[4] { 0.5f * color[0], 0.5f * color[1], 0.5f * color[2], 1.0f }
...

2020-09-16 13:22 UTC, momo5502 commented on src/client/utils/string.hpp
> +	std::vector<std::string> split(std::string& s, char delim);
...

2020-09-16 13:22 UTC, momo5502 commented on src/client/module/game_console.hpp
> +enum ConsoleType
please use snake case

2020-09-16 13:22 UTC, momo5502 commented on src/client/module/game_console.hpp
> +		this->globals = new ConsoleGlobals();
Please no memory leaks

2020-09-16 13:22 UTC, momo5502 commented on src/client/module/game_console.hpp
> +	inline void initialize()
Why inline? Put it in a source file

2020-09-16 13:22 UTC, momo5502 commented on src/client/module/command.cpp
> +    game::native::Cmd_AddCommandInternal(name, callback, new game::native::cmd_function_s);
utils::memory::get_allocator().allocate<game::native::cmd_function_s>();
instead of new game::native::cmd_function_s
That way memory is tracked and not leaked, even though it lives until the end of the process

2020-09-16 13:23 UTC, momo5502 requested changes

2020-09-16 13:23 UTC, momo5502 commented on src/client/module/game_console.cpp
> +float color_white[4] = { 1.0f, 1.0f, 1.0f, 1.0f };
way better

2020-09-17 00:05 UTC, obmiJ commented on src/client/game/game.cpp
> +		void* z_malloc(int size)
removed z_malloc

2020-09-17 06:47 UTC, momo5502 approved these changes

2020-09-17 06:47 UTC, momo5502 commented on src/client/module/game_console.hpp
> +	con_type_error = 1,
Could've kept these in uppercase, but it's fine

2020-09-17 06:47 UTC, merged